[[libcifpp]]
arch = "aarch64"
git-tree-sha1 = "327bb0a109ffb36198eba3b0db9ecc1d06705ed0"
os = "macos"

    [[libcifpp.download]]
    sha256 = "37e34a998c359ab34ef96dd711321ce498839a14aa62de29fc17eece61ab6c1e"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.aarch64-apple-darwin.tar.gz"
[[libcifpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "474fab3c79aaf3829482af1253ef3b35b3ffef9d"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "13a9ddab2a3fd0f445a3eff37b2387fc1ce0cab90bd9a50164011b254c3917bb"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[libcifpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9365a9c14aae5879a9bf4be76793c4635c2c5644"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "a995db3fe28688293d1a0989c2474241e1434f76386afdd16e3b0b873ab8f453"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libcifpp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8385e900d3aa0218575fc47293ed265205d45cf4"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "4c49b10eb3fcd143e17f0089355f5536e87fe7c28339741753507d18cd63a424"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[libcifpp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7936026d4d89d1d1ca4a8c1c6be9da420cd977d6"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "0ba5d41d4e4b8a44e4168f1e32907b97b96bf6256d8a7893ecb95b139492d972"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[libcifpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "003a493a3e312d353f6c306216f30888c8a1f5b4"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "9d506f669d911f060366061cab62aad42ac9430aa5db632d0a59ddcdf383e902"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libcifpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4074a2070b749d6a03df9bbfc7c3eca34b9fdb4b"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "abb57988548d75dc62ace98cdcdd056ad7d9a157012b4e7e45b077ffb5bf7262"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libcifpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9256b692a3cb801db508c02745cff4f8c2425ea2"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "0db1247d761e5a6e56237a55cee06acf0c2135f3a9491346e96b5b88ec38ffb8"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libcifpp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c96d019efcd1e048cef2e7381e5d4706a553be40"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "629285fffbbd77928cfc302f0bcacb00ba1aac57d7e7c00665514ac9f4ca8d4f"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libcifpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b847311008c7c3a289bdfe93e15e86826512681a"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "2f2ad0fc3a1543a1b77ce4642675a7e67307a6fe740d49ee215fe78327201915"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcifpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b59e947048fb7e2cb3f12b7206aeb3d9c2011f3d"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "2c92b3be8a1d1f498b84704774be582acf847e5e0998cc4d7dfb0722a3bed759"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcifpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a13bc847c4becc58da6318945ba348a70848cec8"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "cbb7d246769a30dce9d2cc1d9833e31d5b2e740bc4d051201686bebcacbca35d"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcifpp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74cdde67761ddab8443b6a025d0b9ffce326449c"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "4109cdc123b71204156d47088613096b044c9ec373cd98d75098e7e6dd98ab28"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcifpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2435bf3b92501de26155c09dbbbe149da97badf0"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "723b283e90b8f29394e541ea720d9259c3d9c2f4cec26a88658825e391cbb79e"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.i686-linux-gnu-cxx03.tar.gz"
[[libcifpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37a9536b8e4fe8744f32ae0768da80e3ab5162b8"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "f12cae0418a9cf23bf0d6cd2aa174c336412af11bf9a0f43c7d2eb8aeb73421f"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.i686-linux-gnu-cxx11.tar.gz"
[[libcifpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15e8f42356856b895279e8f49d45c2e1f6c34d72"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "707ef8a6e7705b5fba98ee895d82742f733832471a744288553abfeaaa743799"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.i686-linux-musl-cxx03.tar.gz"
[[libcifpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11e83f79d485321a4be5909ac7cb5c6b2fcd7e5b"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "859107a6f0f587ebcfd9a8654c0d7a14eefa096811f6b86229e9496c4f021277"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.i686-linux-musl-cxx11.tar.gz"
[[libcifpp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76617da3dd203d461e164834b0681a2d87b51130"
os = "windows"

    [[libcifpp.download]]
    sha256 = "2c6d5fa7134b0291e387897e798679914c927bde38a7c6b1492913112ef467c4"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[libcifpp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a39110f638f6bdb5ef4397de9f1f5b2fc0f75990"
os = "windows"

    [[libcifpp.download]]
    sha256 = "df74084d6c0c6339086d64cd3ed1cd4f93bf4a214032d9dd2a5c2a0ed0327e50"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[libcifpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01d4cc72e33454611e0ea117f5a47e4b801099ee"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "7d973400850ba6bbfd1282c9f9e6bfebc47a41ce14d6e6b3db719e66c55572ac"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcifpp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89e09e635ef045bfa46d1af0272ea5c24893e8bd"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "cd753493da9afdfc7e1450ede16d312dbfe8c5ef79557149672f87d00817bad7"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcifpp]]
arch = "x86_64"
git-tree-sha1 = "04a2f93ca5634da8fb095aa098696a3c326a4f97"
os = "macos"

    [[libcifpp.download]]
    sha256 = "00d5f83365c9e9592d622d6c2e5f21abfc36e43c5af9f7148b3a15d927d9661b"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-apple-darwin.tar.gz"
[[libcifpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6c5113f6d33d995fbe9c86b18f3af2241e834070"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "effaaa0f1842eb35e74762d8bf9d08e46230a467c93577615de19ddce143f729"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[libcifpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e61b317f2626b05990a2e3a76a8d051ef23e2a04"
libc = "glibc"
os = "linux"

    [[libcifpp.download]]
    sha256 = "fcafe0e8572d9b866acf451fb10c3598bd11b6871ee4598d5804a9a8cd49978b"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libcifpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81c87ccc03a1bf08b848efa1eac30323ae1df9e7"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "2740e044ca1429ff830987572d6021a2abfcb4553169e656ebcd76a661c440c2"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[libcifpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33c76f891d6931635c93b66bbc40446bfe297b2a"
libc = "musl"
os = "linux"

    [[libcifpp.download]]
    sha256 = "5ddee2f700d29c4f4f57e205ce9858efcb5695afefce2f1fbdf8590ce0cfda32"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[libcifpp]]
arch = "x86_64"
git-tree-sha1 = "e193de3eedc02faa868b0f98104947193d1631c9"
os = "freebsd"

    [[libcifpp.download]]
    sha256 = "cbbb102bbfef8f3290e5909bf82d555bbfce4b6d4f45f7c1504c4a253ed6638f"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-unknown-freebsd.tar.gz"
[[libcifpp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20c21f5dd06fa3aeab0a43355c34f7e758ae4d16"
os = "windows"

    [[libcifpp.download]]
    sha256 = "a3af35fdad38a6f700ca77cd9cb6e07e2a9789f62d1acb4d1814c5a2cce1c647"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcifpp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cec2a92b950a359d3632657526c122a425dca98"
os = "windows"

    [[libcifpp.download]]
    sha256 = "a257954adeee7c80a9e4e146193e09afc575e12b0cdad9b991084a320ef2cc09"
    url = "https://github.com/JuliaBinaryWrappers/libcifpp_jll.jl/releases/download/libcifpp-v5.1.1+0/libcifpp.v5.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
