# Autogenerated wrapper script for libcifpp_jll for aarch64-apple-darwin
export libcifpp

using Zlib_jll
JLLWrappers.@generate_wrapper_header("libcifpp")
JLLWrappers.@declare_library_product(libcifpp, "@rpath/libcifpp.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libcifpp,
        "lib/libcifpp.5.1.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
