# Autogenerated wrapper script for libcifpp_jll for x86_64-w64-mingw32-cxx11
export libcifpp

using Zlib_jll
JLLWrappers.@generate_wrapper_header("libcifpp")
JLLWrappers.@declare_library_product(libcifpp, "libcifpp.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libcifpp,
        "bin\\libcifpp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
